# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=50, verbose_name='活动标题')),
                ('upLoadImg1', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='活动封面')),
                ('newsDetail', models.TextField(max_length=10000, verbose_name='活动详情(图片可以直接粘贴)')),
                ('upLoadImg2', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg3', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg4', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg5', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('viewedTimes', models.IntegerField(default=1, verbose_name='浏览次数')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='apk_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='apk类型')),
            ],
            options={
                'verbose_name': '二维码类型',
                'verbose_name_plural': '二维码类型',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='标题')),
                ('Image', models.FileField(upload_to='core/static/img/', verbose_name='图片（1920*600）')),
                ('Linkto', models.CharField(blank=True, max_length=50, verbose_name='链接地址（可为空）')),
                ('Caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='子标题')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '轮播管理',
                'verbose_name_plural': '轮播管理',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('upLoadImg1', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='活动封面')),
                ('newsDetail', models.TextField(max_length=10000, verbose_name='新闻详情')),
                ('upLoadImg2', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg3', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg4', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg5', models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('viewedTimes', models.IntegerField(default=1, verbose_name='浏览次数')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk', models.FileField(upload_to='core/static/img/', verbose_name='最新apk')),
                ('Linkto', models.CharField(blank=True, max_length=50, verbose_name='ios链接地址（可为空）')),
                ('Image', models.FileField(upload_to='core/static/img/', verbose_name='二维码图片（190*190）')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
                ('apktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apk_type')),
            ],
            options={
                'verbose_name': 'apk下载地址',
                'verbose_name_plural': 'apk下载地址',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='serverno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='大区名')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '新开服务器大区',
                'verbose_name_plural': '新开服务器大区',
                'ordering': ['-dimDate'],
            },
        ),
    ]
