# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='标题')),
                ('Image', models.FileField(upload_to='img/', verbose_name='图片（1920*600）')),
                ('Linkto', models.CharField(blank=True, max_length=50, verbose_name='链接地址（可为空）')),
                ('Caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='子标题')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '轮播管理',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('newsDetail', models.TextField(max_length=10000, verbose_name='新闻详情')),
                ('upLoadImg1', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg2', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg3', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg4', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg5', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('viewedTimes', models.IntegerField(verbose_name='浏览次数')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '新闻',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='img/', verbose_name='图片（496*360）')),
                ('Linkto', models.CharField(blank=True, max_length=50, verbose_name='链接地址（可为空）')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '首页图片新闻',
                'ordering': ['-dimDate'],
            },
        ),
    ]
