# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=50, verbose_name='活动标题')),
                ('newsDetail', models.TextField(max_length=10000, verbose_name='活动详情(图片可以直接粘贴)')),
                ('upLoadImg1', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg2', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg3', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg4', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('upLoadImg5', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式')),
                ('viewedTimes', models.IntegerField(verbose_name='浏览次数')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '活动',
                'ordering': ['-dimDate'],
            },
        ),
    ]
