# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimg',
            name='apk',
        ),
        migrations.AlterField(
            model_name='activities',
            name='newsDetail',
            field=models.TextField(verbose_name='活动详情(图片可以直接粘贴)'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='Image',
            field=models.FileField(upload_to='core/static/img/', verbose_name='图片（详询UI）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsDetail',
            field=models.TextField(verbose_name='新闻详情'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='Linkto',
            field=models.CharField(blank=True, max_length=100, verbose_name='链接地址'),
        ),
    ]
