# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='newsDetail',
            field=models.TextField(verbose_name='活动详情(图片可以直接粘贴)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsDetail',
            field=models.TextField(verbose_name='新闻详情'),
        ),
    ]
