# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linkto', models.CharField(blank=True, max_length=100, verbose_name='链接地址')),
                ('Image', models.FileField(upload_to='core/static/img/', verbose_name='二维码图片（190*190）')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
                ('apktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apk_type')),
            ],
            options={
                'verbose_name_plural': 'apk下载地址',
                'verbose_name': 'apk下载地址',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.AlterField(
            model_name='activities',
            name='newsDetail',
            field=models.TextField(verbose_name='活动详情(图片可以直接粘贴)'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='Image',
            field=models.FileField(upload_to='core/static/img/', verbose_name='图片（详询UI）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsDetail',
            field=models.TextField(verbose_name='新闻详情'),
        ),
    ]
