# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160912_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimg',
            name='apk',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='Image',
            field=models.FileField(upload_to='core/static/img/', verbose_name='图片（详询UI）'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='Linkto',
            field=models.CharField(blank=True, max_length=100, verbose_name='链接地址'),
        ),
    ]
