# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-12 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160912_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='Image',
            field=models.FileField(upload_to='core/static/img/', verbose_name='图片（详询UI）'),
        ),
    ]
