# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='viewedTimes',
            field=models.IntegerField(default=1, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='news',
            name='viewedTimes',
            field=models.IntegerField(default=1, verbose_name='浏览次数'),
        ),
    ]
