# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160912_1145'),
        ('core', '0004_auto_20160912_1444'),
    ]

    operations = [
    ]
