# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160906_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='upLoadImg1',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='活动封面'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='upLoadImg2',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='upLoadImg3',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='upLoadImg4',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='upLoadImg5',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传活动中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='Image',
            field=models.FileField(upload_to='core/static/img/', verbose_name='图片（1920*600）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='upLoadImg1',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='活动封面'),
        ),
        migrations.AlterField(
            model_name='news',
            name='upLoadImg2',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='news',
            name='upLoadImg3',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='news',
            name='upLoadImg4',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='news',
            name='upLoadImg5',
            field=models.FileField(blank=True, null=True, upload_to='core/static/img/', verbose_name='上传新闻中的图片，引用图片请采用"/static/img/xxx.xx"格式'),
        ),
        migrations.AlterField(
            model_name='newsimg',
            name='Image',
            field=models.FileField(upload_to='core/static/img/', verbose_name='图片（496*360）'),
        ),
    ]
