# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160906_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='大区名')),
                ('Linkto', models.CharField(blank=True, max_length=50, verbose_name='链接地址（可为空）')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dimDate'],
                'verbose_name': '新开服务器大区',
            },
        ),
        migrations.AlterModelOptions(
            name='newsimg',
            options={'ordering': ['-dimDate'], 'verbose_name': 'apk下载地址'},
        ),
        migrations.RemoveField(
            model_name='newsimg',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='newsimg',
            name='Linkto',
        ),
        migrations.AddField(
            model_name='newsimg',
            name='apk',
            field=models.FileField(default='', upload_to='core/static/img/', verbose_name='最新apk'),
            preserve_default=False,
        ),
    ]
